#!/usr/bin/env groovy
pipeline {
    agent any

    tools {nodejs "my node"}

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh "echo hello"
                dir("tommasobellini-front") {
                    sh 'npm run build'
                }
                echo 'Built...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                dir("tommasobellini-front") {
                    sh 'npm install -g firebase-tools'
                    sh 'firebase deploy --token "1/6bm1x3XMPf1VzgJG-uW2ekLlxCm9knPdATplHaWG8twpj8B9uSTWXH7vnryZrvLi"'                   
                }
                echo 'Deployed'
            }
        }
    }
}