#!/usr/bin/env groovy
pipeline {
    agent any

    tools {nodejs "my node"}

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh "echo hello"
                dir("tommasobellini-front") {
                    sh 'npm install'
                    sh 'npm run build'
                    sh 'git config git-ftp.syncroot dist/'
                    sh 'npm install git-ftp'
                    sh 'git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.tommasobellini.it/htdocs'
                    sh 'git ftp push'
                }
                echo 'Built...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                dir("tommasobellini-front") {
                    sh 'npm install -g firebase-tools'
                    sh 'firebase deploy --token $FIREBASE_TOKEN'
                }
                echo 'Deployed'
            }
        }
    }
}